apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rcds
rules:
- apiGroups: [""]
  resources: ["services", "namespaces", "configmaps"]
  verbs: ["list", "get", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets"]
  verbs: ["list", "get", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["list", "get", "watch", "create", "update", "patch", "delete"]
